# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
    ]
